version: '3.8'

services:
  ceesarcode:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - GO_ENV=production
    volumes:
      # Mount data directory for persistent problems
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/problems"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #   - "6379:6379"
  #   volumes:
  #   - redis_data:/data

volumes:
  redis_data:
